### ISSUE TITLE
Fedora２３下还是无法验证。。。

### ISSUE THREAD

**Issue by Sevyyy** [zlsun/yah3c#1]
==> Sending EAPOL start
==> Got EAP Request for identity
==> Sending EAP response with identity = [wangq248]
==> Got EAP Request for MD5-Challenge
==> Sending EAP response with password
==> Got EAP Request for MD5-Challenge
==> Sending EAP response with password
==> Got EAP Failure
求破。。

**Comment by yutouyes** [comment]
raspbian jessie下正常，是不是你没有执行 python3 setup.py install？你应该以前也装过旧版yah3c吧，可能是没更换成yah3c-py3

**Comment by zlsun** [comment]
你能用 wireshark 抓下包吗，只有这些信息无法判断问题的原因

**Comment by Sevyyy** [comment]
@yutouyes 不好意思，忘了是用python3运行..........

**Comment by zlsun** [comment]
我已经在 README 里加上需要 python3 的说明，这个 Issue 我就关了
