### ISSUE TITLE
反复出现Got EAP Request for identity无法认证

### ISSUE THREAD

**Issue by songfeil** [zlsun/yah3c#3]
你好，试图使用yah3c在中东拨号后，一直反复出现如下错误，无法继续认证
==> Sending EAPOL start
==> Got EAP Request for identity
==> Sending EAP response with identity = [songfl3]
==> Got EAP Request for identity
==> Sending EAP response with identity = [songfl3]
==> Got EAP Request for identity
==> Sending EAP response with identity = [songfl3]
==> Got EAP Request for identity
==> Sending EAP response with identity = [songfl3]
==> Got EAP Request for identity
==> Sending EAP response with identity = [songfl3]

**Comment by zlsun** [comment]
从日志上，我看不出哪里出问题了。你可以先尝试以下步骤：
1. 检查 /etc/yah3c.conf 的格式和内容是否正确 (格式参考 [README.md](https://github.com/zlsun/yah3c#配置) ) 。
2. 重启电脑，再次认证。

**Comment by songfeil** [comment]
谢谢，经排查后是因为使用了错误的网卡接口eth0，路由器上网线接口为eth0.2，现已经能正常拨号了，谢谢！

**Comment by zlsun** [comment]
不客气，既然问题解决了我就关掉这个 Issue 了。
